### ISSUE TITLE
Issue with ' in ssl_ciphers

### ISSUE THREAD

**Issue by namurdock** [noodlemctwoodle/Wiki-Config-Container#1]
Looks like a leading ' is causing validation issues in the example config.

https://github.com/noodlemctwoodle/Wiki-Config-Container/blob/811c246bc300117d1840c63ddac27b4e4d26ecfc/nginx/container-proxy-configs/nginx-containers#L20

Replaced with:

`ssl_ciphers               ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256;
    `

**Comment by noodlemctwoodle** [comment]
Removed erroneous leading back tick, thanks for spotting this.
