### ISSUE TITLE
Streamlined script for cert generation

### ISSUE THREAD

**Issue by namurdock** [noodlemctwoodle/Wiki-Config-Container#2]
Whenever i go to create a cert and Nginx in running there is a contention on port 80. So i have added a pre and post hook to streamline things...

` ./letsencrypt-auto certonly --standalone --pre-hook "service nginx stop" --post-hook "service nginx start" --expand -d <url1>,<url2>....
`

**Comment by noodlemctwoodle** [comment]
Updated [Create Certificate/s](https://github.com/noodlemctwoodle/Hassio/wiki/Guide---NGINX-&-Lets-Encrypt#create-certificates) wiki with streamlined command. 

Thanks
